language: r
cache: packages
r_check_args: --as-cran 
r_build_args: --compact-vignettes=both

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

before_install:
  - export DISPLAY=:99.0

apt_packages:
  - libgl1-mesa-dev 
  - libglu1-mesa-dev

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'
    